export const categories = ['Water & Plumbing','Electricity','Cleanliness','Furniture','Internet/Wi-Fi','Road & Pathway','Safety','Other'] as const;
export const statuses = ['Pending','In Progress','Resolved','Rejected'] as const;
export const priorities = ['Low','Medium','High'] as const;
export const departments = ['Maintenance','Electrical','Housekeeping','IT Support','Security','Other'] as const;
export type Recommendation = {category:string;priority:string;department:string;reason:string};
export type Report = {id:string;reportId:string;title:string;description:string;category:string;priority:string;location:string;imageUrl:string;status:string;department:string;aiRecommendation:Recommendation|null;adminNote:string;createdBy:string;createdAt:string;updatedAt:string;updates:{status:string;note:string;department:string;at:string}[]};
export function analyze(description:string):Recommendation {
 const t=description.toLowerCase();
 const rules:[RegExp,string,string][]=[[/water|leak|plumb|washroom|cooler/,'Water & Plumbing','Maintenance'],[/wi.?fi|internet|network/,'Internet/Wi-Fi','IT Support'],[/electric|light|fan|wire|power/,'Electricity','Electrical'],[/garbage|trash|dirty|waste|clean/,'Cleanliness','Housekeeping'],[/chair|desk|furniture|table/,'Furniture','Maintenance'],[/path|road|pothole|pavement/,'Road & Pathway','Maintenance'],[/unsafe|security|danger/,'Safety','Security']];
 const match=rules.find(([r])=>r.test(t));const category=match?.[1]??'Other',department=match?.[2]??'Other';
 const priority=/slip|unsafe|danger|exposed|spark|flood|major|outage/.test(t)?'High':/minor|cosmetic|scratch/.test(t)?'Low':'Medium';
 return {category,department,priority,reason:priority==='High'?'The description mentions a potential safety concern or service disruption. Please ask an administrator to review.':`The description relates to ${category.toLowerCase()} and should be reviewed by ${department.toLowerCase()}.`};
}
export function seeds():Report[]{
 const rows=[['Broken water cooler','Block 34','Water & Plumbing','High','In Progress','Maintenance'],['Broken classroom fan','Block 12 · Room 204','Electricity','Medium','Pending','Electrical'],['Garbage accumulation','Hostel C','Cleanliness','Medium','Resolved','Housekeeping'],['Campus Wi-Fi outage','Central Library','Internet/Wi-Fi','High','In Progress','IT Support'],['Broken pathway light','Main Gate','Electricity','High','Pending','Electrical'],['Loose chair in lecture hall','Block 26 · Room 102','Furniture','Low','Resolved','Maintenance'],['Uneven paving stones','Sports Complex','Road & Pathway','Medium','Pending','Maintenance'],['Water tap needs repair','Hostel B','Water & Plumbing','Medium','Resolved','Maintenance']];
 return rows.map((r,i)=>{const at=new Date(Date.now()-(i+1)*86400000).toISOString();return {id:`seed-${i}`,reportId:`CF-2026-${String(i+1).padStart(5,'0')}`,title:r[0],location:r[1],category:r[2],priority:r[3],status:r[4],department:r[5],description:`${r[0]} at ${r[1]}. Please arrange an inspection and the necessary repairs.`,imageUrl:'',aiRecommendation:null,adminNote:r[4]==='Resolved'?'The team has completed the work. Thank you for reporting.':r[4]==='In Progress'?'The department has been assigned and inspection is underway.':'',createdBy:i<5?'student-demo':'campus-demo',createdAt:at,updatedAt:at,updates:[{status:'Pending',note:'Report submitted.',department:'Other',at},...(r[4]!=='Pending'?[{status:r[4],note:r[4]==='Resolved'?'Work completed by the department.':'Team assigned for inspection.',department:r[5],at:new Date(new Date(at).getTime()+3600000).toISOString()}]:[])]};});
}
